version: '3'

volumes:
  front_build_volume:

networks:
  recipe-app-net:

services:

  frontend:
    build: ./frontend-server
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - /app/node_modules
      - ./frontend-server:/app
      - front_build_volume:/app/build
    networks:
      - recipe-app-net

  backend:
    build: ./backend-server
    depends_on:
      - frontend
    ports:
      - 3001:3001
    restart: unless-stopped
    volumes:
      - /app/node_modules
      - ./backend-server:/app
      - front_build_volume:/app/build/frontend
    env_file:
      - docker.env
    networks:
      - recipe-app-net

  database:
    container_name: postgresql_database_omnia
    depends_on:
      - backend
    image: postgres:16.1
    restart: unless-stopped
    env_file:
      - docker.env
    networks:
      - recipe-app-net

  flyway:
    image: flyway/flyway:10.8.1
    env_file:
      - docker.env
    depends_on:
      - database
    volumes:
      - ./flyway/sql:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    networks:
      - recipe-app-net